version: "3.8"

databases:
  - name: apicrud_cai3
    databaseName: apicrud_cai3
    user: apicrud_cai3_user

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=apicrud
    ports:
      - '5432:5432'

  apicrud:
    container_name: conta
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8085:80'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/apicrud
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234567890
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres

  pgbouncer:
    type: pserv
    name: pgbouncer
    runtime: docker
    plan: standard
    repo: https://github.com/render-oss/docker-pgbouncer
    envVars:
      - key: DATABASE_URL
        value: jdbc:postgres://apicrud_cai3_user:D3aZso7mO0twyAzzEboaqh80DT0ehDnF@dpg-cn70la8l5elc738jru9g-a/apicrud_cai3
        fromDatabase:
          name: apicrud_cai3
          property: connectionString
      - key: POOL_MODE
        value: transaction
      - key: SERVER_RESET_QUERY
        value: DISCARD ALL
      - key: MAX_CLIENT_CONN
        value: 500
      - key: DEFAULT_POOL_SIZE
        value: 50
